#!/usr/bin/env python3
"""Rasterize original Figma vectors at 2x into LVGL alpha masks (resvg)."""
from pathlib import Path
import subprocess
import io
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS = {
    'page_empty': ('04bb89831753fefa490c2f5f42e7fa18d712ad66', 24, 24),
    'page_full': ('69a5999be30457036893feb0a4bb60e1406463ba', 24, 24),
    'face_outline': ('003ab956bf84be3ebc5e3433bdf6100f2c43cc32', 240, 240),
    'eye_sleep': ('73a240328c0af832429ec826d95866828a98ef12', 46, 19),
    'eye_happy': ('dea1f5ea9cdd5beedbd529f0de1ac37a88fc525d', 52, 30),
    'smile': ('15942160e0864f9a425f0a6590db84709eb3de55', 93, 26),
    'face_listening': ('24d43d10cfa2b2899d99179290d5516b087bca32', 240, 240),
    'ears': ('c6ede54d62f60089137caf23df7076eaac30b05e', 224, 368),
    'face_thinking': ('28ecaa798fa488d23c4046e753e1dfed112d6b48', 240, 240),
    'face_attention': ('e164d2114f2b230b286a381f498179cf435bc2ea', 240, 240),
}

def main():
    output = ['// Generated by scripts/design-assets.py from original Figma SVGs.', '#include "lvgl.h"']
    header = ['#pragma once', '#include "lvgl.h"']
    for name, (asset, width, height) in ASSETS.items():
        png = subprocess.check_output(['node', str(ROOT / 'scripts/render-svg.cjs'),
            str(ROOT / 'assets/figma' / (asset + '.svg')), str(width)])
        bitmap = Image.open(io.BytesIO(png)).convert('RGBA').resize((width, height))
        data = bitmap.getchannel('A').tobytes()
        assert len(data) == width * height
        # Compact the padded sound-wave frame before embedding.
        x0, y0, x1, y1 = 0, 0, width, height
        if name == 'ears':
            points = [(i % width, i // width) for i, value in enumerate(data) if value]
            x0, y0 = min(p[0] for p in points), min(p[1] for p in points)
            x1, y1 = max(p[0] for p in points) + 1, max(p[1] for p in points) + 1
        cropped = b''.join(data[y * width + x0:y * width + x1] for y in range(y0, y1))
        width, height = x1 - x0, y1 - y0
        assert any(cropped), name
        output += [f'static const uint8_t {name}_pixels[] = {{']
        output += ['    ' + ','.join(str(b) for b in cropped[i:i+32]) + ',' for i in range(0, len(cropped), 32)]
        output += ['};', f'const lv_image_dsc_t pip_{name} = {{',
            f'    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = {width}, .h = {height}, .stride = {width}}},',
            f'    .data_size = sizeof({name}_pixels), .data = {name}_pixels,', '};']
        header += [f'extern const lv_image_dsc_t pip_{name};']
        if name == 'ears':
            flipped = b''.join(cropped[y * width:(y + 1) * width][::-1] for y in range(height))
            output += ['static const uint8_t ears_left_pixels[] = {']
            output += ['    ' + ','.join(str(b) for b in flipped[i:i+32]) + ',' for i in range(0, len(flipped), 32)]
            output += ['};', 'const lv_image_dsc_t pip_ears_left = {',
                f'    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = {width}, .h = {height}, .stride = {width}}},',
                '    .data_size = sizeof(ears_left_pixels), .data = ears_left_pixels,', '};']
            header += ['extern const lv_image_dsc_t pip_ears_left;']
        print(name, width, height, 'offset', x0, y0)
    (ROOT / 'components/pip_board/pip_assets.c').write_text('\n'.join(output) + '\n')
    (ROOT / 'components/pip_board/pip_assets.h').write_text('\n'.join(header) + '\n')

if __name__ == '__main__':
    main()
